name: Build & Test

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

env:
    BUILD_TYPE: Release

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install SFML
              run: sudo apt-get -y install libsfml-dev

            - name: Install tmxlite
              run: |
                  git clone https://github.com/fallahn/tmxlite
                  cd tmxlite/tmxlite
                  mkdir build && cd build
                  cmake .. -DTMXLITE_STATIC_LIB=TRUE
                  sudo make install
                  cd ${{github.workspace}}

            - name: Configure CMake
              run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

            - name: Build
              run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target=all.test

            - name: Test
              run: ${{github.workspace}}/build/all.test
